# Generated by Django 3.2.4 on 2021-07-08 21:50

import datetime
import django.core.validators
from django.db import migrations
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0039_auto_20210611_1044'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=salesforce.fields.CharField(db_column='hed__Course_ID__c', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=salesforce.fields.CharField(choices=[('WE', 'Weekend'), ('CA', 'Camp'), ('SP', 'Special')], db_column='Course_Type__c', default='WE', max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=salesforce.fields.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=salesforce.fields.TextField(blank=True, db_column='hed__Extended_Description__c', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=salesforce.fields.TimeField(db_column='Duration__c', default=datetime.timedelta(seconds=10800), help_text='HH:MM:ss'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=salesforce.fields.CharField(auto_created=True, db_column='Id', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=salesforce.fields.BooleanField(db_column='Active__c', default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='maximum_age',
            field=salesforce.fields.IntegerField(db_column='Maximum_Age__c', default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='minimum_age',
            field=salesforce.fields.IntegerField(db_column='Minimum_Age__c', default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=salesforce.fields.CharField(db_column='Name', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=salesforce.fields.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterModelTable(
            name='course',
            table='hed__Course__c',
        ),
    ]
