# Generated by Django 3.2.5 on 2021-07-14 21:34

import coderdojochi.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0039_auto_20210611_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdcuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='meetingorder',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='mentororder',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='session',
            name='waitlist_mentors',
        ),
        migrations.RemoveField(
            model_name='session',
            name='waitlist_students',
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, upload_to=coderdojochi.models.user.generate_filename),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='avatar_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='background_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='ethnicity',
            field=models.CharField(choices=[('Hispanic', 'Hispanic'), ('Not Hispanic', 'Not Hispanic')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='race',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='work_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingorder',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentororder',
            name='user',
            field=models.ForeignKey(default='', limit_choices_to={'user__role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, to='coderdojochi.cdcuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdcuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='assistant',
            field=models.ManyToManyField(blank=True, help_text="A mentor with 'Assistant' role, is active (user and mentor), background check passed, and avatar approved.", limit_choices_to={'avatar_approved': True, 'background_check': True, 'is_active': True, 'user__groups__name': 'Assistant', 'user__is_active': True, 'user__role': 'mentor'}, related_name='session_assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(help_text="A mentor with 'Instructor' role, is active (user and mentor), background check passed, and avatar approved.", limit_choices_to={'avatar_approved': True, 'background_check': True, 'is_active': True, 'user__groups__name': 'Instructor', 'user__is_active': True, 'user__role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
