# Generated by Django 3.2.5 on 2021-07-14 20:17

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0039_auto_20210611_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdcuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'managed': True, 'verbose_name': 'equipment', 'verbose_name_plural': 'equipment'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': True, 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='meetingorder',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='meetingtype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'managed': True},
        ),
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='donation',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equipment',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='equipmenttype',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='guardian',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='meeting',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='meetingorder',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='meetingtype',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='mentororder',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='session',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='race_ethnicity',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='zip',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='meetingorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meetingorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='meetingtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meetingtype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='meetingtype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mentororder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mentororder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='alternate_guardian',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='bg_image',
        ),
        migrations.RemoveField(
            model_name='session',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='override_maximum_age_limitation',
        ),
        migrations.RemoveField(
            model_name='session',
            name='override_minimum_age_limitation',
        ),
        migrations.RemoveField(
            model_name='session',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='session',
            name='waitlist_mentors',
        ),
        migrations.RemoveField(
            model_name='session',
            name='waitlist_students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='race_ethnicity',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='avatar_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='background_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='ethnicity',
            field=models.CharField(choices=[('Hispanic', 'Hispanic'), ('Not Hispanic', 'Not Hispanic')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='race',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='work_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guardian',
            name='ethnicity',
            field=salesforce.fields.CharField(choices=[('Hispanic', 'Hispanic'), ('Not Hispanic', 'Not Hispanic')], db_column='hed__Ethnicity__c', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='guardian',
            name='race',
            field=salesforce.fields.CharField(db_column='hed__Race__c', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='ethnicity',
            field=salesforce.fields.CharField(choices=[('Hispanic', 'Hispanic'), ('Not Hispanic', 'Not Hispanic')], db_column='hed__Ethnicity__c', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='race',
            field=salesforce.fields.CharField(db_column='hed__Race__c', default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cdcuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=salesforce.fields.CharField(db_column='hed__Course_ID__c', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=salesforce.fields.CharField(choices=[('WE', 'Weekend'), ('CA', 'Camp'), ('SP', 'Special')], db_column='Course_Type__c', default='WE', max_length=2, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=salesforce.fields.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=salesforce.fields.TextField(blank=True, db_column='hed__Extended_Description__c', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=salesforce.fields.TimeField(db_column='Duration__c', default=datetime.timedelta(seconds=10800), help_text='HH:MM:ss'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=salesforce.fields.CharField(auto_created=True, db_column='Id', editable=False, max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=salesforce.fields.BooleanField(db_column='Active__c', default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='maximum_age',
            field=salesforce.fields.IntegerField(db_column='Maximum_Age__c', default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='minimum_age',
            field=salesforce.fields.IntegerField(db_column='Minimum_Age__c', default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=salesforce.fields.CharField(db_column='Name', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=salesforce.fields.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=salesforce.fields.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=salesforce.fields.EmailField(blank=True, db_column='Email__c', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='first_name',
            field=salesforce.fields.CharField(blank=True, db_column='First_Name__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_verified',
            field=salesforce.fields.BooleanField(db_column='Is_Verified__c', default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='last_name',
            field=salesforce.fields.CharField(blank=True, db_column='Last_Name__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='receipt_sent',
            field=salesforce.fields.BooleanField(db_column='Receipt_Sent__c', default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='referral_code',
            field=salesforce.fields.CharField(blank=True, db_column='Referral_Code__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='session',
            field=salesforce.fields.ForeignKey(blank=True, db_column='Course_Offering__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coderdojochi.session'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=salesforce.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='acquisition_date',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Acquisition_Date__c', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_tag',
            field=salesforce.fields.CharField(db_column='Asset_Tag__c', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=salesforce.fields.CharField(choices=[('working', 'Working'), ('issue', 'Issue'), ('unusable', 'Unusable')], db_column='Condition__c', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=salesforce.fields.ForeignKey(db_column='Type__c', on_delete=django.db.models.deletion.DO_NOTHING, to='coderdojochi.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='force_update_on_next_boot',
            field=salesforce.fields.BooleanField(db_column='Force_Update_Next__c', default=False, verbose_name='Force Update'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_system_update',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Last_System_Update__c', null=True, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='last_system_update_check_in',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Last_System_Update_Check__c', null=True, verbose_name='Last Check In'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='make',
            field=salesforce.fields.CharField(db_column='Make__c', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model',
            field=salesforce.fields.CharField(db_column='Model__c', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=salesforce.fields.TextField(blank=True, db_column='Notes__c', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='uuid',
            field=salesforce.fields.CharField(db_column='uuid__c', default='000-000-000-000', max_length=255, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=salesforce.fields.CharField(db_column='Name__c', max_length=255),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='birthday',
            field=salesforce.fields.DateField(db_column='Birthdate', null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='gender',
            field=salesforce.fields.CharField(db_column='Gender__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='is_active',
            field=salesforce.fields.BooleanField(db_column='Active__c', default=False),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=salesforce.fields.CharField(blank=True, db_column='Phone', max_length=50),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='user',
            field=salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=salesforce.fields.CharField(blank=True, db_column='hed__MailingStreet__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=salesforce.fields.CharField(blank=True, db_column='hed__MailingCity__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_active',
            field=salesforce.fields.BooleanField(db_column='Active__c', default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=salesforce.fields.CharField(db_column='Address_Name__c', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=salesforce.fields.CharField(blank=True, db_column='hed__MailingState__c', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=salesforce.fields.CharField(blank=True, db_column='hed__MailingPostalCode__c', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='additional_info',
            field=salesforce.fields.TextField(blank=True, db_column='Additional_Information__c', help_text='Basic HTML allowed', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='announced_date',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Announced_Date__c', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_date',
            field=salesforce.fields.DateTimeField(blank=True, db_column='End_Date__c', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='external_enrollment_url',
            field=salesforce.fields.CharField(blank=True, db_column='External_Enrollment_URL__c', help_text='When provided, local enrollment is disabled.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='image_url',
            field=salesforce.fields.CharField(blank=True, db_column='Image_URL__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_active',
            field=salesforce.fields.BooleanField(db_column='Is_Active__c', default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_public',
            field=salesforce.fields.BooleanField(db_column='Is_Public__c', default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='location',
            field=salesforce.fields.ForeignKey(db_column='Address__c', default='', on_delete=django.db.models.deletion.PROTECT, to='coderdojochi.location'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=salesforce.fields.ForeignKey(db_column='Meeting_Type__c', on_delete=django.db.models.deletion.PROTECT, to='coderdojochi.meetingtype'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Start_Date__c', null=True),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='affiliate',
            field=salesforce.fields.CharField(blank=True, db_column='Affiliate__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='check_in',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Check_In__c', null=True),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='day_reminder_sent',
            field=salesforce.fields.BooleanField(db_column='Day_Reminder_Sent__c', default=False),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='ip',
            field=salesforce.fields.CharField(blank=True, db_column='IP__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='is_active',
            field=salesforce.fields.BooleanField(db_column='Is_Active__c', default=False),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='meeting',
            field=salesforce.fields.ForeignKey(db_column='Meeting__c', on_delete=django.db.models.deletion.PROTECT, to='coderdojochi.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='mentor',
            field=salesforce.fields.ForeignKey(db_column='Mentor__c', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='order_number',
            field=salesforce.fields.CharField(blank=True, db_column='Order_Number__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingorder',
            name='week_reminder_sent',
            field=salesforce.fields.BooleanField(db_column='Week_Reminder_Sent__c', default=False),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='code',
            field=salesforce.fields.CharField(blank=True, db_column='Code__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='description',
            field=salesforce.fields.TextField(blank=True, db_column='Description__c', help_text='Basic HTML allowed', null=True),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingtype',
            name='title',
            field=salesforce.fields.CharField(db_column='Title__c', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='affiliate',
            field=salesforce.fields.CharField(blank=True, db_column='Affiliate__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='check_in',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Check_in__c', null=True),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='day_reminder_sent',
            field=salesforce.fields.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='ip',
            field=salesforce.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='is_active',
            field=salesforce.fields.CharField(blank=True, choices=[('current', 'current'), ('former', 'former')], db_column='hed__Status__c', max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='mentor',
            field=salesforce.fields.ForeignKey(db_column='hed__Contact__c', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='order_number',
            field=salesforce.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='session',
            field=salesforce.fields.ForeignKey(db_column='hed__Course_Offering__c', on_delete=django.db.models.deletion.PROTECT, to='coderdojochi.session'),
        ),
        migrations.AlterField(
            model_name='mentororder',
            name='week_reminder_sent',
            field=salesforce.fields.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='affiliate',
            field=salesforce.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_in',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Check_in__c', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='day_reminder_sent',
            field=salesforce.fields.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=salesforce.fields.CharField(blank=True, db_column='IP__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=salesforce.fields.CharField(blank=True, choices=[('current', 'current'), ('former', 'former')], db_column='hed__Status__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=salesforce.fields.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='session',
            field=salesforce.fields.ForeignKey(db_column='hed__Course_Offering__c', on_delete=django.db.models.deletion.PROTECT, to='coderdojochi.session'),
        ),
        migrations.AlterField(
            model_name='order',
            name='student',
            field=salesforce.fields.ForeignKey(db_column='hed__Contact__c', on_delete=django.db.models.deletion.PROTECT, to='coderdojochi.student'),
        ),
        migrations.AlterField(
            model_name='order',
            name='week_reminder_sent',
            field=salesforce.fields.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='additional_info',
            field=salesforce.fields.TextField(blank=True, db_column='Additional_Information__c', help_text='Basic HTML allowed', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='announced_date_guardians',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Announced_Date_Guardians__c', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='announced_date_mentors',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Announce_Date_Mentors__c', null=True),
        ),
        migrations.RemoveField(
            model_name='session',
            name='assistant',
        ),
        migrations.AddField(
            model_name='session',
            name='assistant',
            field=salesforce.fields.ForeignKey(blank=True, db_column='Assistant_Mentor__c', help_text="A mentor with 'Assistant' role, is active (user and mentor), background check passed, and avatar approved.", limit_choices_to={'avatar_approved': True, 'background_check': True, 'is_active': True, 'user__groups__name': 'Assistant', 'user__is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_assistant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='capacity',
            field=salesforce.fields.IntegerField(db_column='hed__Capacity__c', default=20),
        ),
        migrations.AlterField(
            model_name='session',
            name='cost',
            field=salesforce.fields.DecimalField(blank=True, db_column='Cost__c', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=salesforce.fields.ForeignKey(db_column='hed__Course__c', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='coderdojochi.course'),
        ),
        migrations.AlterField(
            model_name='session',
            name='external_enrollment_url',
            field=salesforce.fields.CharField(blank=True, db_column='External_Enrollment_URL__c', help_text='When provided, local enrollment is disabled.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='gender_limitation',
            field=salesforce.fields.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], db_column='Gender_Limitation__c', help_text='Limits the class to be only one gender.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='image_url',
            field=salesforce.fields.CharField(blank=True, db_column='Image_URL__c', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=salesforce.fields.ForeignKey(db_column='hed__Faculty__c', help_text="A mentor with 'Instructor' role, is active (user and mentor), background check passed, and avatar approved.", limit_choices_to={'avatar_approved': True, 'background_check': True, 'is_active': True, 'user__groups__name': 'Instructor', 'user__is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='session_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=salesforce.fields.BooleanField(db_column='Active__c', default=False, help_text='Session is active.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_public',
            field=salesforce.fields.BooleanField(db_column='Public__c', default=False, help_text='Session is a public session.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=salesforce.fields.ForeignKey(db_column='Offering_Location__c', default='', on_delete=django.db.models.deletion.PROTECT, to='coderdojochi.location'),
        ),
        migrations.AlterField(
            model_name='session',
            name='maximum_cost',
            field=salesforce.fields.DecimalField(blank=True, db_column='Maximum_Cost__c', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentor_capacity',
            field=salesforce.fields.IntegerField(db_column='Mentor_Capacity__c', default=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentors_day_reminder_sent',
            field=salesforce.fields.BooleanField(db_column='Mentor_Day_Reminder_Sent__c', default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='mentors_week_reminder_sent',
            field=salesforce.fields.BooleanField(db_column='Mentor_Week_Reminder_Sent__c', default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='minimum_cost',
            field=salesforce.fields.DecimalField(blank=True, db_column='Minimum_Cost__c', decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='old_end_date',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Old_End_Date__c', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='old_mentor_end_date',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Old_Mentor_End_Date__c', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='old_mentor_start_date',
            field=salesforce.fields.DateTimeField(blank=True, db_column='Old_Mentor_Start__c', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='online_video_description',
            field=salesforce.fields.TextField(blank=True, db_column='Online_Video_Description__c', help_text='Information on how to connect to the video call. Basic HTML allowed.', null=True, verbose_name='Online Video Description'),
        ),
        migrations.AlterField(
            model_name='session',
            name='online_video_link',
            field=salesforce.fields.URLField(blank=True, db_column='Online_Video_Link__c', help_text='Zoom link with password.', null=True, verbose_name='Online Video Link'),
        ),
        migrations.AlterField(
            model_name='session',
            name='online_video_meeting_id',
            field=salesforce.fields.CharField(blank=True, db_column='Online_Video_Meeting_Id__c', help_text='XXX XXXX XXXX', max_length=255, null=True, verbose_name='Online Video Meeting ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='online_video_meeting_password',
            field=salesforce.fields.CharField(blank=True, db_column='Online_Video_Meeting_Password__c', help_text='Plain text password shared by Zoom', max_length=255, null=True, verbose_name='Online Video Meeting Password'),
        ),
        migrations.AlterField(
            model_name='session',
            name='partner_message',
            field=salesforce.fields.TextField(blank=True, db_column='Partner_Message__c'),
        ),
        migrations.AlterField(
            model_name='session',
            name='password',
            field=salesforce.fields.CharField(blank=True, db_column='Password__c', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=salesforce.fields.DateField(db_column='hed__Start_Date__c'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=salesforce.fields.DateField(db_column='Birthdate'),
        ),
        migrations.AlterField(
            model_name='student',
            name='consent',
            field=salesforce.fields.BooleanField(db_column='Consent__c', default='General Consent', help_text='I hereby give consent for the student signed up above to participate in We All Code.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=salesforce.fields.CharField(db_column='FirstName', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=salesforce.fields.CharField(db_column='Gender__c', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian',
            field=salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coderdojochi.guardian'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=salesforce.fields.BooleanField(db_column='Active__c', default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=salesforce.fields.CharField(db_column='LastName', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_conditions',
            field=salesforce.fields.TextField(blank=True, db_column='Medical__c', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='medications',
            field=salesforce.fields.TextField(blank=True, db_column='Medications__c', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo_release',
            field=salesforce.fields.BooleanField(db_column='Photo_Release__c', default='Photo Consent', help_text="I hereby give permission to We All Code to use the student's image and/or likeness in promotional materials."),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=salesforce.fields.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_type',
            field=salesforce.fields.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='course',
            table='hed__Course__c',
        ),
        migrations.AlterModelTable(
            name='donation',
            table='Donation__c',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='Equipment__c',
        ),
        migrations.AlterModelTable(
            name='equipmenttype',
            table='Equipment_Type__c',
        ),
        migrations.AlterModelTable(
            name='guardian',
            table='Contact',
        ),
        migrations.AlterModelTable(
            name='location',
            table='hed__Address__c',
        ),
        migrations.AlterModelTable(
            name='meeting',
            table='Meeting__c',
        ),
        migrations.AlterModelTable(
            name='meetingorder',
            table='Meeting_Order__c',
        ),
        migrations.AlterModelTable(
            name='meetingtype',
            table='Meeting_Type__c',
        ),
        migrations.AlterModelTable(
            name='mentororder',
            table='hed__Course_Enrollment__c',
        ),
        migrations.AlterModelTable(
            name='order',
            table='hed__Course_Enrollment__c',
        ),
        migrations.AlterModelTable(
            name='session',
            table='hed__Course_Offering__c',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Contact',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
