# Generated by Django 3.2.4 on 2021-07-09 22:15

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0039_auto_20210611_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', salesforce.fields.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Test_Model__c',
                'managed': True,
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='HelloWorldModel',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('body', salesforce.fields.TextField()),
                ('test', salesforce.fields.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coderdojochi.testmodel')),
            ],
            options={
                'db_table': 'Hello_World_Model__c',
                'managed': True,
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
