# Generated by Django 3.2.5 on 2021-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0040_auto_20210714_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdcuser',
            name='email',
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
