# Generated by Django 3.2.5 on 2021-07-15 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coderdojochi', '0042_auto_20210715_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdcuser',
            name='consent',
            field=models.BooleanField(blank=True, default=False, help_text='I hereby give consent for the student signed up above to participate in We All Code.', verbose_name='General Consent'),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__role': 'guardian'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_guardian', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='photo_release',
            field=models.BooleanField(blank=True, default=False, help_text="I hereby give permission to We All Code to use the student's image and/or likeness in promotional materials.", verbose_name='Photo Consent'),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='school_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cdcuser',
            name='school_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cdcuser',
            name='role',
            field=models.CharField(choices=[('mentor', 'mentor'), ('guardian', 'guardian'), ('student', 'student')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='guardian',
            field=models.ForeignKey(limit_choices_to={'user__role': 'guardian'}, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user__role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
